### ISSUE TITLE
Camera Center

### ISSUE THREAD

**Issue by kevincador** [NYTimes/ios-360-videos#50]
Hi,

Installed the 360 player via cocoapods and first things we saw was that the camera seems not to be centered correctly on the front facing side of the 360 video.

Saw a Pull request for it so we integrated the modification locally but it's not on cocoapods. Do you plan to release a new version soon?

Regards,

Kevin

**Comment by cdzombak** [comment]
I just released [v1.1.0](https://github.com/NYTimes/ios-360-videos/tree/1.1.0) which includes that fix.
