### ISSUE TITLE
Example video fails due to credential

### ISSUE THREAD

**Issue by jagatfx** [NYTimes/ios-360-videos#65]
When attempting to run the sample project on iOS 11.3 with Xcode 9.3. The example [video URL](https://github.com/NYTimes/ios-360-videos/blob/develop/NYT360VideoExample/ViewController.m#L28) (`https://vp.nyt.com/video/360/hls/video.m3u8`) fails to load and the console shows:

```
2018-04-24 16:20:13.539335+0800 NYT360VideoExample[6285:2948864] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}
```

After adjusting to a freely available video URL, the video plays fine.

**Comment by thiagopnts** [comment]
fixed thanks!
